apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "33060"
    port: 33060
    targetPort: 3306
  selector:
    service: db
