apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wikinetwork
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          network/wikinetwork: "true"
  podSelector:
    matchLabels:
      network/wikinetwork: "true"
